<a href="https://colab.research.google.com/github/BrothaaEww/ML-Basics/blob/main/ML_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a =[1,4,9,16,25,36,49,64,81,100]

In [ ]:
a1=[i**2 for i in range(10)]

In [ ]:
a= [10,-2,13,-5,3,0,1,-2]
# b= [x for x in a if x<0 0 if x> 0]

b=[0 if x<0 else x for x in a]
print(b)

[10, 0, 13, 0, 3, 0, 1, 0]


In [ ]:
from math import pi
pi=str(pi)
a = [float('3.'+pi[2:i]) for i in range(3,len(pi)) ]
print(a)

[3.1, 3.14, 3.141, 3.1415, 3.14159, 3.141592, 3.1415926, 3.14159265, 3.141592653, 3.1415926535, 3.14159265358, 3.141592653589, 3.1415926535897, 3.14159265358979]


In [ ]:
a=[[1,2],[3,4],[5,6]]
b = [[a[i][j]for i in range(len(a))] for j in range(len(a[1]))]
b

[[1, 3, 5], [2, 4, 6]]

In [ ]:
s ={1,2,3}
hash(s)

In [ ]:
d = {('ram', 'sharma'):[13,10,9]}
for i in d:
  # print(i)
  print(f" {' '.join(list(i))} has scored {d[i][0]} in math {d[i][1]} in physics and {d[i][2]} in chem")
# print(d.items())
for (fn,ln),(p,c,m) in d.items():
  print(f" {fn + ' '+ ln} has scored {m} in math {p} in physics and {c} in chem")

 ram sharma has scored 13 in math 10 in physics and 9 in chem
 ram sharma has scored 9 in math 13 in physics and 10 in chem


vararg function: function with variable number of arguments
\* will make it a tuple
tuple can take n number of positional arguments but it cannot take n number of keyword arguments
... so ** will make it a dictionary

In [ ]:
def factorial(n):
  return 1 if n==0 else n*factorial(n-1)

In [ ]:
def factorials(*nums):
  facts=[]
  for n in nums:
    facts.append(factorial(n))
  return facts

print(f'{factorials(*[1,2,3])}')

[1, 2, 6]


In [ ]:
def pp(**kwargs):
  for x, y in kwargs.items():
    print(f'x : {x}\ny : {y}')

pp(x=10000, y = "dbdfvf")

generators : it is an object that can generate a sequence of items

before creating generator obj we need to create a generator function
a generator is lazily evaluated. when a function call is made then a generator is onject is returned
generator can generate only once

In [ ]:
def factorial(n):
  f = 1
  for i in range(1,n+1):
    f*=i
    yield f

f = factorial(5)
print(f)
print(type(f))

<generator object factorial at 0x7f2474289460>
<class 'generator'>


In [ ]:
for n in f:
  print(n)

In [ ]:
n = list(factorial(5))
n

In [ ]:
def names(english = True):
  if english:
    yield 'tom'
    yield 'lebu'
    yield 'nashpati'
  else:
    yield 'sobeda'
    yield 'kola'
    yield 'badaam'

In [ ]:
for name in names(False):
  print(name)

sobeda
kola
badaam


In [ ]:
Names = ['ram','sam','jodhu']
ages = [10,11,12]
sals= [100000,1212,111]

z = zip(Names,ages,sals)
print(z)

In [ ]:
for i in zip(Names,ages,sals):
  print(i)

('ram', 10, 100000)
('sam', 11, 1212)
('jodhu', 12, 111)


In [ ]:
def fibonacci_generator(n):
  if n <= 0:
    return
  yield 0
  if n == 1:
    return
  yield 1
  a, b = 0, 1
  while n>2:
    c = a + b
    yield c
    a, b = b, c
    n-=1

for i in fibonacci_generator(10):
  print(i)

In [ ]:
a = [10,5,4,2,1,6]

In [ ]:
for items in map(factorial,a):
  print(items)

In [ ]:
def print_name():
    print('Geoffrey Hinton')

def name_decorator(f):
    def decorate_name():
        print('Dr.', end = '')
        f()
    return decorate_name

In [ ]:
import numpy as np
a = np.array([[1,2,3,9,11,23,344,55],
              [4,5,6,8,23,223,33,222],
              [7,8,9,7,23,45,67,67],
              [12,23,34,34,34,3,1,2],
              [1,2,3,4,5,6,7,8]])
print(a[:,[1,2,5]][[1,2,4],:])

[[  5   6 223]
 [  8   9  45]
 [  2   3   6]]


In [ ]:
@np.vectorize
def factorialn(n):
  return 1 if n==0 else n*factorialn(n-1)

factorialn(5)

array(120)

In [ ]:
vec_fact = np.vectorize(factorialn)

In [ ]:
a = np.random.randint(1,10,(5,6))
# print(a)
# print(vec_fact(a))

factorialn(a)

array([[     1,   5040,  40320,      6,  40320,  40320],
       [     2,      6,     24, 362880, 362880,   5040],
       [     1,      2, 362880,    120, 362880,     24],
       [ 40320,    120,  40320,  40320,    720,      2],
       [ 40320,     24,    120,     24,      2,   5040]])

In [ ]:
import numpy as np
a = np.random.randint(1,100,(5,6))
print(a)
print(a[(a>50) & (a<10)])

In [ ]:
import numpy as np
A = np.array([[3,2,-1],
              [2,-2,4],
              [-1,0.5,-1]])
B = np.array([1,-2,0])

X = np.linalg.solve(A,B)
print(X)

[ 1. -2. -2.]


In [ ]:
np.allclose(A @ X, B)

True

In [ ]:
np.linalg.inv(A) @ B

array([ 1., -2., -2.])

In [ ]:
import numpy as np
import pandas as pd

s1 = pd.Series({'ram':1,'sam':2,'bantu':3,'begun':4})
print(s1)

ram      1
sam      2
bantu    3
begun    4
dtype: int64


In [ ]:
s1.index

Index(['ram', 'sam', 'bantu', 'begun'], dtype='object')

In [ ]:
s1.values

array([1, 2, 3, 4])

In [ ]:
s2 = pd.Series([12,3,45,67,78,1,22,12])

In [ ]:
print(s2)

In [ ]:
s2.index

In [ ]:
s3 = pd.Series([12,3,45,67], index = ['ram', 'sam', 'bantu', 'begun'])

In [ ]:
print(s3)

In [ ]:
d1 = pd.DataFrame({'Tom': [12, 6, 8], 'John': [13, 8 ,3], 'Harry': [98,5,7], 'Bill': [76,2,12]}, index = ['physics','chemistry','mathematics'])
d1

In [ ]:
d2 = pd.DataFrame(np.random.randint(0,101,(10,5)), index = [ 's' + str(i) for i in range (1,11)], columns = ['phy','chem','math','bio','comp'])

In [ ]:
d2['s1':'s5':2]

In [ ]:
d2.loc['s1':'s5':2,['chem','bio']]

In [ ]:
d2.iloc[1:6:2,[1,3]]

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
housing = pd.read_csv('/content/housing1.csv')
housing.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [ ]:
housing.iloc[:20]

In [ ]:
# housing.info()
housing['ocean_proximity'].value_counts()

<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: ocean_proximity, dtype: int64

In [ ]:
housing['ocean_proximity'].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [ ]:
#categoric attributes are converted to numerical attributes for the machine to learn
housing.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [ ]:
housing.describe().transpose()

count           mean            std         min  \
longitude           20640.0    -119.569704       2.003532   -124.3500   
latitude            20640.0      35.631861       2.135952     32.5400   
housing_median_age  20640.0      28.639486      12.585558      1.0000   
total_rooms         20640.0    2635.763081    2181.615252      2.0000   
total_bedrooms      20433.0     537.870553     421.385070      1.0000   
population          20640.0    1425.476744    1132.462122      3.0000   
households          20640.0     499.539680     382.329753      1.0000   
median_income       20640.0       3.870671       1.899822      0.4999   
median_house_value  20640.0  206855.816909  115395.615874  14999.0000   

                            25%          50%           75%          max  
longitude             -121.8000    -118.4900    -118.01000    -114.3100  
latitude                33.9300      34.2600      37.71000      41.9500  
housing_median_age      18.0000      29.0000      37.00000      52.0000  
total_rooms           1447.7500    2127.0000    3148.00000   39320.0000  
total_bedrooms         296.0000     435.0000     647.00000    6445.0000  
population             787.0000    1166.0000    1725.00000   35682.0000  
households             280.0000     409.0000     605.00000    6082.0000  
median_income            2.5634       3.5348       4.74325      15.0001  
median_house_value  119600.0000  179700.0000  264725.00000  500001.0000

all the features are continuous random variables with probability density curves for all

In [ ]:
housing.hist(bins=60,figsize = (20,15))

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test = train_test_split(housing,test_size=0.2)

In [ ]:
X_train.shape

(16512, 10)

In [ ]:
X_test.shape

(4128, 10)

**stratified shuffle split** : the ratio is maintained as same as that of the original dataset

1.divide the dataset into homogeneious datasets (every homogeneous set is called a stratum)
2.randomly choose from individual starta and then place them in the train set to preserve the ratio

thus, approximately the ratio is maintained at the *end*

the corellations between all the features(independent value with the depenednt value) is calculated to find the most influencial feature

In [ ]:
#pearson corelation
corr = housing.corr() #correlation between every feature is given

<ipython-input-10-b1217a549336>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr = housing.corr() #correlation between every feature is given


In [ ]:
corr

longitude  latitude  housing_median_age  total_rooms  \
longitude            1.000000 -0.924664           -0.108197     0.044568   
latitude            -0.924664  1.000000            0.011173    -0.036100   
housing_median_age  -0.108197  0.011173            1.000000    -0.361262   
total_rooms          0.044568 -0.036100           -0.361262     1.000000   
total_bedrooms       0.069608 -0.066983           -0.320451     0.930380   
population           0.099773 -0.108785           -0.296244     0.857126   
households           0.055310 -0.071035           -0.302916     0.918484   
median_income       -0.015176 -0.079809           -0.119034     0.198050   
median_house_value  -0.045967 -0.144160            0.105623     0.134153   

                    total_bedrooms  population  households  median_income  \
longitude                 0.069608    0.099773    0.055310      -0.015176   
latitude                 -0.066983   -0.108785   -0.071035      -0.079809   
housing_median_age       -0.320451   -0.296244   -0.302916      -0.119034   
total_rooms               0.930380    0.857126    0.918484       0.198050   
total_bedrooms            1.000000    0.877747    0.979728      -0.007723   
population                0.877747    1.000000    0.907222       0.004834   
households                0.979728    0.907222    1.000000       0.013033   
median_income            -0.007723    0.004834    0.013033       1.000000   
median_house_value        0.049686   -0.024650    0.065843       0.688075   

                    median_house_value  
longitude                    -0.045967  
latitude                     -0.144160  
housing_median_age            0.105623  
total_rooms                   0.134153  
total_bedrooms                0.049686  
population                   -0.024650  
households                    0.065843  
median_income                 0.688075  
median_house_value            1.000000

In [ ]:
corr['median_house_value'].sort_values(ascending = False)

#for median_house_value, median_income is the most important feature
# median_income is a nmeric feature so it has infinite possibilities , so we need a categorial feature(say income_category)

median_house_value    1.000000
median_income         0.688075
total_rooms           0.134153
housing_median_age    0.105623
households            0.065843
total_bedrooms        0.049686
population           -0.024650
longitude            -0.045967
latitude             -0.144160
Name: median_house_value, dtype: float64

In [ ]:
np.min(housing['median_income'])

0.4999

In [ ]:
np.max(housing['median_income'])

15.0001

divide every income by 1.5 and take its ceiling value

In [ ]:
housing['income_cat'] = np.ceil(housing['median_income']/1.5)

In [ ]:
housing['income_cat'].value_counts().sort_index()

1.0      822
2.0     6581
3.0     7236
4.0     3639
5.0     1423
6.0      532
7.0      189
8.0      105
9.0       50
10.0      14
11.0      49
Name: income_cat, dtype: int64

merging 6.0 to 11.0

In [ ]:
housing['income_cat'].where(housing['income_cat'] < 5, 5, inplace = True)

In [ ]:
housing['income_cat'].value_counts().sort_index()

1.0     822
2.0    6581
3.0    7236
4.0    3639
5.0    2362
Name: income_cat, dtype: int64

In [ ]:
housing['income_cat'].value_counts().sort_index()/len(housing['income_cat'])

1.0    0.039826
2.0    0.318847
3.0    0.350581
4.0    0.176308
5.0    0.114438
Name: income_cat, dtype: float64

In [ ]:
from sklearn.model_selection import StratifiedShuffleSplit

In [ ]:
strat_split = StratifiedShuffleSplit(n_splits = 1, test_size = 0.2, random_state = 42)

In [ ]:
strat_split

StratifiedShuffleSplit(n_splits=1, random_state=42, test_size=0.2,
            train_size=None)

In [ ]:
for train_ix, test_ix in strat_split.split(housing, housing['income_cat']):
  strat_train_split = housing.iloc[train_ix]
  strat_test_split = housing.iloc[test_ix]

In [ ]:
strat_train_split['income_cat'].value_counts().sort_index()/len(strat_train_split['income_cat'])

1.0    0.039789
2.0    0.318859
3.0    0.350594
4.0    0.176296
5.0    0.114462
Name: income_cat, dtype: float64

In [ ]:
strat_test_split['income_cat'].value_counts().sort_index()/len(strat_test_split['income_cat'])

1.0    0.039971
2.0    0.318798
3.0    0.350533
4.0    0.176357
5.0    0.114341
Name: income_cat, dtype: float64

In [ ]:
strat_train_split = strat_train_split.drop('income_cat', axis = 1)
strat_test_split = strat_test_split.drop('income_cat', axis = 1)

In [ ]:
X_train = strat_train_split.drop('median_house_value', axis = 1)
Y_train = strat_train_split['median_house_value']

X_test = strat_test_split.drop('median_house_value', axis = 1)
Y_test = strat_test_split['median_house_value']

In [ ]:
X_train.shape

(16512, 9)

In [ ]:
X_test.shape

(4128, 9)

In [ ]:
X_train_numeric = X_train.drop('ocean_proximity', axis = 1)
X_train_cat = X_train['ocean_proximity']

In [ ]:
X_train_numeric.info()

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'median')

In [ ]:
imputer.fit(X_train_numeric)

SimpleImputer(strategy='median')

In [ ]:
imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [ ]:
X_train_numeric_ndarray = imputer.transform(X_train_numeric)

In [ ]:
# X_train_numeric_ndarray.info

In [ ]:
X_train_numeric_ndarray_df = pd.DataFrame(X_train_numeric_ndarray, columns = X_train_numeric.columns)

In [ ]:
X_train_numeric_ndarray_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16512 entries, 0 to 16511
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16512 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
dtypes: float64(8)
memory usage: 1.0 MB


In [ ]:
from sklearn.preprocessing import MinMaxScaler

In [ ]:
minMaxScaler = MinMaxScaler()

In [ ]:
X_train_numeric_min_max_scaled = minMaxScaler.fit_transform(X_train_numeric_ndarray)

In [ ]:
X_train_numeric_min_max_scaled[:5]

array([[0.28784861, 0.63549416, 0.54901961, 0.09836191, 0.12806057,
        0.06261386, 0.13144137, 0.11542599],
       [0.70916335, 0.05844846, 0.11764706, 0.13516813, 0.13740335,
        0.05639172, 0.14301718, 0.40257376],
       [0.52888446, 0.30074389, 0.84313725, 0.0410032 , 0.0496134 ,
        0.01861039, 0.05563854, 0.16379774],
       [0.71912351, 0.02231668, 0.45098039, 0.04759119, 0.08327964,
        0.02508478, 0.08980583, 0.11906732],
       [0.562749  , 0.18490967, 0.50980392, 0.0897899 , 0.10373711,
        0.05140279, 0.10791636, 0.27561689]])

**standard scaler**

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train_numeric_ndarray_scaled = scaler.fit_transform(X_train_numeric_ndarray)

**ORDINAL ENCODING**

In [ ]:
X_train_cat.unique()

In [ ]:
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
ord_encoder = OrdinalEncoder()

In [ ]:
X_train_cat_ord_encoded = ord_encoder.fit_transform(X_train_cat.values.reshape(-1,1))

In [ ]:
X_train_cat_ord_encoded[:200]

In [ ]:
ord_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

**ONE HOT ENCODING**

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
hot_encoder = OneHotEncoder()

In [ ]:
X_train_cat_hot_encoded = hot_encoder.fit_transform(X_train_cat.values.reshape(-1,1))

In [ ]:
X_train_cat_hot_encoded.toarray()[:5]

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [ ]:
X_train_cat_hot_encoded_1 = pd.get_dummies(X_train_cat)

In [ ]:
X_train_cat_hot_encoded_1[:5]

<1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
12655          0       1       0         0           0
15502          0       0       0         0           1
2908           0       1       0         0           0
14053          0       0       0         0           1
20496          1       0       0         0           0

In [ ]:
X_train_final = np.c_[X_train_numeric_ndarray_scaled,X_train_cat_hot_encoded.toarray()]

In [ ]:
X_train_final.shape

(16512, 13)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
lin_reg = LinearRegression()

In [ ]:
lin_reg.fit(X_train_final,Y_train)

LinearRegression()

In [ ]:
y_pred_5 = lin_reg.predict(X_train_final[:5])

In [ ]:
Y_train[:5]

12655     72100.0
15502    279600.0
2908      82700.0
14053    112500.0
20496    238300.0
Name: median_house_value, dtype: float64

In [ ]:
y_pred_5[:5]

array([ 88983.14806384, 305351.35385026, 153334.71183453, 184302.55162102,
       246840.18988841])

In [ ]:
Y_pred = lin_reg.predict(X_train_final)

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
mean_squared_error(Y_train,Y_pred)

4767980139.451871

In [ ]:
np.sqrt(mean_squared_error(Y_train,Y_pred))

69050.56219504567

**PIPELINING**

**CUSTOM TRANSFORMER**

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin

In [ ]:
class DataFrameSelector(BaseEstimator,TransformerMixin):
  def __init__(self,columns=[]):
    self.columns = columns
  def fit(self,X, Y=None):
    return self
  def transform(self,X):
    return X[self.columns]

In [ ]:
dfs = DataFrameSelector(columns=['ocean_proximity'])
col = dfs.fit_transform(X_train)
col.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 16512 entries, 12655 to 19773
Data columns (total 1 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   ocean_proximity  16512 non-null  object
dtypes: object(1)
memory usage: 258.0+ KB


In [ ]:
from sklearn.pipeline import Pipeline, FeatureUnion

In [ ]:
num_pipe = Pipeline([('selector', DataFrameSelector(columns = X_train.columns[:-1])),
                     ('imputer', SimpleImputer(strategy = 'median')),
                     ('scaler', StandardScaler())])
cat_pipe =  Pipeline([('selector', DataFrameSelector(columns =['ocean_proximity'])),
                     ('hot_encoder', OneHotEncoder(sparse = False))])
full_pipe = FeatureUnion([('num_pipe', num_pipe),('cat_pipe', cat_pipe)])

In [ ]:
X_train_final_1 = full_pipe.fit_transform(X_train)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
X_test_final_1 = full_pipe.fit_transform(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [ ]:
lin_reg.fit(X_train_final_1, Y_train)

LinearRegression()

In [ ]:
y_test_preds = lin_reg.predict(X_test_final_1)

In [ ]:
mean_squared_error(Y_test,y_test_preds)

4536582124.8658285

In [ ]:
X_train_final_1.shape

(16512, 13)

In [ ]:
Y_train.shape

(16512,)

**K FOLD CROSS VALIDATION**

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
neg_mses = cross_val_score(lin_reg , X_train_final, Y_train, cv = 8, scoring = 'neg_mean_squared_error')

In [ ]:
mses = -neg_mses

In [ ]:
rmses = np.sqrt(mses)

In [ ]:
rmses

array([70974.67235533, 68465.30252367, 66225.0789892 , 67584.98743315,
       71881.16802866, 70746.33976234, 67947.94577765, 70110.53691487])

**HYPERPARAMETER TUNING**

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = [
    {'n_estimators':[3,10,30],'max_features':[2,4,6,8]},
    {'bootstrap':[False],'n_estimators':[3,10],'max_features':[2,3,4]}
]

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
cv = GridSearchCV(RandomForestRegressor(), param_grid, cv=8, scoring = 'neg_mean_squared_error')

In [ ]:
cv.fit(X_train_final,Y_train)

GridSearchCV(cv=8, estimator=RandomForestRegressor(),
             param_grid=[{'max_features': [2, 4, 6, 8],
                          'n_estimators': [3, 10, 30]},
                         {'bootstrap': [False], 'max_features': [2, 3, 4],
                          'n_estimators': [3, 10]}],
             scoring='neg_mean_squared_error')

In [ ]:
cv.best_params_

{'max_features': 6, 'n_estimators': 30}

In [ ]:
model = cv.best_estimator_

In [ ]:
model

RandomForestRegressor(max_features=6, n_estimators=30)